replicaCount: 3

image:
  repository: redis
  tag: "7.2"
  pullPolicy: IfNotPresent

exporter:
  enabled: true
  image:
    repository: oliver006/redis_exporter
    tag: "v1.55.0"
    pullPolicy: IfNotPresent
  port: 9121

service:
  port: 6379

auth:
  enabled: true
  username: redis
  password: "redis"

persistence:
  enabled: true
  size: 2Gi
  storageClass: ""
  mountPath: /data


resources: {}
